name: Reset Neon dev branch from main nightly
on:
  schedule:
    - cron: "0 8 * * *" # 08:00 UTC daily
  workflow_dispatch: {}

jobs:
  reset-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Install neonctl v2
        run: npm i -g neonctl@v2

      - name: Reset dev branch from parent
        env:
          NEON_API_KEY: ${{ secrets.NEON_API_KEY }}
          NEON_API_HOST: https://console.neon.tech/api/v2
        run: |
          set -euo pipefail
          # Reset the *branch* from its parent
          neonctl branches reset "${{ vars.NEON_DEV_BRANCH_ID }}" \
            --project-id "${{ vars.NEON_PROJECT_ID }}" \
            --parent \
            --output json > branch_out

          echo "branch reset out:"; cat branch_out

      - name: Output connection strings for neondb (direct + pooled)
        id: cs
        env:
          NEON_API_KEY: ${{ secrets.NEON_API_KEY }}
          NEON_API_HOST: https://console.neon.tech/api/v2
        run: |
          set -euo pipefail
          # Direct (non-pooled) URL for neondb
          CS_JSON=$(neonctl cs \
            --project-id "${{ vars.NEON_PROJECT_ID }}" \
            --database-name neondb \
            --extended -o json)
          # Pooled URL for neondb
          CS_JSON_POOLED=$(neonctl cs \
            --project-id "${{ vars.NEON_PROJECT_ID }}" \
            --database-name neondb \
            --extended -o json --pooled)

          DIRECT_URL=$(echo "$CS_JSON" | jq -r '.connection_string')
          POOLED_URL=$(echo "$CS_JSON_POOLED" | jq -r '.connection_string')

          echo "direct_url=$DIRECT_URL" >> "$GITHUB_OUTPUT"
          echo "pooled_url=$POOLED_URL"   >> "$GITHUB_OUTPUT"

      - name: Show outputs (for quick copy)
        run: |
          echo "DIRECT_URL: ${{ steps.cs.outputs.direct_url }}"
          echo "DATABASE_URL (pooled): ${{ steps.cs.outputs.pooled_url }}"
